#!/bin/sh

# der volle Pfad des directories in dem dieses build Skript liegt
this_path="$(dirname "$(readlink -f "$0")")"

cat "$this_path/edit_bashrc" | awk -v new_line="base64_addition='$(base64 --wrap=0 "$this_path/bashrc_addition")'" 'NR==6 {$0=new_line} {print}' > "$this_path/edit_bashrc.tmp"

cat "$this_path/installer" | awk -v new_line="base64_payload='$(base64 --wrap=0 "$this_path/edit_bashrc.tmp")'" 'NR==3 {$0=new_line} {print}' > "$this_path/zell.sh"

chmod +x "$this_path/zell.sh"
rm "$this_path/edit_bashrc.tmp"
